from __future__ import annotations
version: str

class Response:
    def __init__(self) -> None: ...
    def execute(self, __payload:bytes | bytearray | memoryview[int]) -> int:...
    def pause(self) -> None:...
    def unpause(self) -> None:...
    def upgrade(self) -> None:...
    def finish(self) -> None:...
    def reset(self) -> None:...
    def on_message_begin(self) -> None:...
    def on_protocol(self, data:bytes) -> None:...
    def on_url(self, data:bytes) -> None:...
    def on_status(self, data:bytes) -> None:...
    def on_method(self, data:bytes) -> None:...
    def on_version(self, data:bytes) -> None:...
    def on_header_field(self, data:bytes) -> None:...
    def on_header_value(self, data:bytes) -> None:...
    def on_chunk_extension_name(self, data:bytes) -> None:...
    def on_chunk_extension_value(self, data:bytes) -> None:...
    def on_headers_complete(self) -> None:...
    def on_body(self, data:bytes) -> None:...
    def on_message_complete(self) -> None:...
    def on_protocol_complete(self) -> None:...
    def on_url_complete(self) -> None:...
    def on_status_complete(self) -> None:...
    def on_method_complete(self) -> None:...
    def on_version_complete(self) -> None:...
    def on_header_field_complete(self) -> None:...
    def on_header_value_complete(self) -> None:...
    def on_chunk_extension_name_complete(self) -> None:...
    def on_chunk_extension_value_complete(self) -> None:...
    def on_chunk_header(self) -> None:...
    def on_chunk_complete(self) -> None:...
    def on_reset(self) -> None:...

    method:str 
    major:int 
    minor:int 
    status:int
    content_length: int
    lenient_headers:bool
    lenient_chunked_length:bool
    lenient_keep_alive:bool
    lenient_transfer_encoding:bool
    lenient_version:bool
    lenient_data_after_close: bool
    lenient_lf_after_cr: bool 
    lenient_optional_crlf_after_chunk: bool
    lenient_optional_cr_before_lf:bool
    lenient_spaces_after_chunk_size:int
    message_needs_eof: bool 
    should_keep_alive:bool
    is_paused:bool
    is_upgrading:bool
    is_busted:bool
    error:str

class Request:
    def __init__(self) -> None: ...
    def execute(self, __payload:bytes | bytearray | memoryview[int]) -> int:...
    def pause(self) -> None:...
    def unpause(self) -> None:...
    def upgrade(self) -> None:...
    def finish(self) -> None:...
    def reset(self) -> None:...
    def on_message_begin(self) -> None:...
    def on_protocol(self, data:bytes) -> None:...
    def on_url(self, data:bytes) -> None:...
    def on_status(self, data:bytes) -> None:...
    def on_method(self, data:bytes) -> None:...
    def on_version(self, data:bytes) -> None:...
    def on_header_field(self, data:bytes) -> None:...
    def on_header_value(self, data:bytes) -> None:...
    def on_chunk_extension_name(self, data:bytes) -> None:...
    def on_chunk_extension_value(self, data:bytes) -> None:...
    def on_headers_complete(self) -> None:...
    def on_body(self, data:bytes) -> None:...
    def on_message_complete(self) -> None:...
    def on_protocol_complete(self) -> None:...
    def on_url_complete(self) -> None:...
    def on_status_complete(self) -> None:...
    def on_method_complete(self) -> None:...
    def on_version_complete(self) -> None:...
    def on_header_field_complete(self) -> None:...
    def on_header_value_complete(self) -> None:...
    def on_chunk_extension_name_complete(self) -> None:...
    def on_chunk_extension_value_complete(self) -> None:...
    def on_chunk_header(self) -> None:...
    def on_chunk_complete(self) -> None:...
    def on_reset(self) -> None:...

    method:str 
    major:int 
    minor:int 
    status:int
    content_length: int
    lenient_headers:bool
    lenient_chunked_length:bool
    lenient_keep_alive:bool
    lenient_transfer_encoding:bool
    lenient_version:bool
    lenient_data_after_close: bool
    lenient_lf_after_cr: bool 
    lenient_optional_crlf_after_chunk: bool
    lenient_optional_cr_before_lf:bool
    lenient_spaces_after_chunk_size:int
    message_needs_eof: bool 
    should_keep_alive:bool
    is_paused:bool
    is_upgrading:bool
    is_busted:bool
    error:str
